language: java
before_script:
  - echo "Starting build"
script:
  - mvn clean package
after_script:
  - echo "Build is ready"
  - ls -l $TRAVIS_BUILD_DIR/target
after_failure:
  - echo "Build failure"